# Generated by Django 2.2.4 on 2019-12-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(default="Default", max_length=255, unique=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("debug_mode", models.BooleanField(default=True)),
                ("secret_key", models.CharField(blank=True, max_length=255)),
                ("append_slash", models.BooleanField(default=False)),
                (
                    "allowed_hosts",
                    models.CharField(
                        blank=True,
                        help_text="A comma-delimited list of hosts for which this application is allowed to respond to.",
                        max_length=255,
                    ),
                ),
            ],
            options={"verbose_name": "Settings", "verbose_name_plural": "Settings"},
        ),
    ]
